'use strict';
const Country = require('../app/region/Country');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    // Заполнение таблицы Cities
    const CountryRows = await Country.findAll();

    const citiesData = [
      // Россия
      { name: 'Moscow', CountryId: CountryRows[0].id },
      { name: 'Saint Petersburg', CountryId: CountryRows[0].id },
      { name: 'Novosibirsk', CountryId: CountryRows[0].id },
      { name: 'Yekaterinburg', CountryId: CountryRows[0].id },
      { name: 'Nizhny Novgorod', CountryId: CountryRows[0].id },
      { name: 'Kazan', CountryId: CountryRows[0].id },
      { name: 'Chelyabinsk', CountryId: CountryRows[0].id },
      { name: 'Omsk', CountryId: CountryRows[0].id },
      { name: 'Samara', CountryId: CountryRows[0].id },
      { name: 'Rostov-on-Don', CountryId: CountryRows[0].id },
      // Украина
      { name: 'Kyiv', CountryId: CountryRows[1].id },
      { name: 'Kharkiv', CountryId: CountryRows[1].id },
      { name: 'Odesa', CountryId: CountryRows[1].id },
      { name: 'Dnipro', CountryId: CountryRows[1].id },
      { name: 'Donetsk', CountryId: CountryRows[1].id },
      { name: 'Zaporizhzhia', CountryId: CountryRows[1].id },
      { name: 'Lviv', CountryId: CountryRows[1].id },
      { name: 'Kryvyi Rih', CountryId: CountryRows[1].id },
      { name: 'Mykolaiv', CountryId: CountryRows[1].id },
      { name: 'Mariupol', CountryId: CountryRows[1].id },
      // Беларусь
      { name: 'Minsk', CountryId: CountryRows[2].id },
      { name: 'Gomel', CountryId: CountryRows[2].id },
      { name: 'Mogilev', CountryId: CountryRows[2].id },
      { name: 'Vitebsk', CountryId: CountryRows[2].id },
      { name: 'Hrodna', CountryId: CountryRows[2].id },
      { name: 'Brest', CountryId: CountryRows[2].id },
      { name: 'Babruysk', CountryId: CountryRows[2].id },
      { name: 'Baranovichi', CountryId: CountryRows[2].id },
      { name: 'Pinsk', CountryId: CountryRows[2].id },
      { name: 'Orsha', CountryId: CountryRows[2].id },
      // Казахстан
      { name: 'Almaty', CountryId: CountryRows[3].id },
      { name: 'Nur-Sultan', CountryId: CountryRows[3].id },
      { name: 'Shymkent', CountryId: CountryRows[3].id },
      { name: 'Karaganda', CountryId: CountryRows[3].id },
      { name: 'Aktobe', CountryId: CountryRows[3].id },
      { name: 'Taraz', CountryId: CountryRows[3].id },
      { name: 'Pavlodar', CountryId: CountryRows[3].id },
      { name: 'Ust-Kamenogorsk', CountryId: CountryRows[3].id },
      { name: 'Semey', CountryId: CountryRows[3].id },
      { name: 'Kostanay', CountryId: CountryRows[3].id },
      // Узбекистан
      { name: 'Tashkent', CountryId: CountryRows[4].id },
      { name: 'Namangan', CountryId: CountryRows[4].id },
      { name: 'Samarkand', CountryId: CountryRows[4].id },
      { name: 'Andijan', CountryId: CountryRows[4].id },
      { name: 'Bukhara', CountryId: CountryRows[4].id },
      { name: 'Nukus', CountryId: CountryRows[4].id },
      { name: 'Urgench', CountryId: CountryRows[4].id },
      { name: 'Fergana', CountryId: CountryRows[4].id },
      { name: 'Qarshi', CountryId: CountryRows[4].id },
      { name: 'Jizzakh', CountryId: CountryRows[4].id },
      // Туркменистан
      { name: 'Ashgabat', CountryId: CountryRows[5].id },
      { name: 'Turkmenabat', CountryId: CountryRows[5].id },
      { name: 'Dashoguz', CountryId: CountryRows[5].id },
      { name: 'Mary', CountryId: CountryRows[5].id },
      { name: 'Balkanabat', CountryId: CountryRows[5].id },
      { name: 'Bayramaly', CountryId: CountryRows[5].id },
      { name: 'Tejen', CountryId: CountryRows[5].id },
      { name: 'Bereket', CountryId: CountryRows[5].id },
      { name: 'Kaka', CountryId: CountryRows[5].id },
      { name: 'Atamyrat', CountryId: CountryRows[5].id },
      // Киргизия
      { name: 'Bishkek', CountryId: CountryRows[6].id },
      { name: 'Osh', CountryId: CountryRows[6].id },
      { name: 'Jalal-Abad', CountryId: CountryRows[6].id },
      { name: 'Karabalta', CountryId: CountryRows[6].id },
      { name: 'Tokmok', CountryId: CountryRows[6].id },
      { name: 'Kara-Balta', CountryId: CountryRows[6].id },
      { name: 'Naryn', CountryId: CountryRows[6].id },
      { name: 'Talas', CountryId: CountryRows[6].id },
      { name: 'Karakol', CountryId: CountryRows[6].id },
      { name: 'Batken', CountryId: CountryRows[6].id },
      // Таджикистан
      { name: 'Dushanbe', CountryId: CountryRows[7].id },
      { name: 'Khujand', CountryId: CountryRows[7].id },
      { name: 'Kulob', CountryId: CountryRows[7].id },
      { name: 'Qurghonteppa', CountryId: CountryRows[7].id },
      { name: 'Istaravshan', CountryId: CountryRows[7].id },
      { name: 'Konibodom', CountryId: CountryRows[7].id },
      { name: 'Tursunzoda', CountryId: CountryRows[7].id },
      { name: 'Isfara', CountryId: CountryRows[7].id },
      { name: 'Panjakent', CountryId: CountryRows[7].id },
      { name: 'Vahdat', CountryId: CountryRows[7].id },
      // Армения
      { name: 'Yerevan', CountryId: CountryRows[8].id },
      { name: 'Gyumri', CountryId: CountryRows[8].id },
      { name: 'Vanadzor', CountryId: CountryRows[8].id },
      { name: 'Hrazdan', CountryId: CountryRows[8].id },
      { name: 'Abovyan', CountryId: CountryRows[8].id },
      { name: 'Kapan', CountryId: CountryRows[8].id },
      { name: 'Armavir', CountryId: CountryRows[8].id },
      { name: 'Stepanavan', CountryId: CountryRows[8].id },
      { name: 'Gavar', CountryId: CountryRows[8].id },
      { name: 'Artashat', CountryId: CountryRows[8].id },
      // Азербайджан
      { name: 'Baku', CountryId: CountryRows[9].id },
      { name: 'Ganja', CountryId: CountryRows[9].id },
      { name: 'Sumqayit', CountryId: CountryRows[9].id },
      { name: 'Mingachevir', CountryId: CountryRows[9].id },
      { name: 'Lankaran', CountryId: CountryRows[9].id },
      { name: 'Shirvan', CountryId: CountryRows[9].id },
      { name: 'Nakhchivan', CountryId: CountryRows[9].id },
      { name: 'Shaki', CountryId: CountryRows[9].id },
      { name: 'Yevlakh', CountryId: CountryRows[9].id },
      { name: 'Gabala', CountryId: CountryRows[9].id },
      // Грузия
      { name: 'Tbilisi', CountryId: CountryRows[10].id },
      { name: 'Kutaisi', CountryId: CountryRows[10].id },
      { name: 'Batumi', CountryId: CountryRows[10].id },
      { name: 'Rustavi', CountryId: CountryRows[10].id },
      { name: 'Zugdidi', CountryId: CountryRows[10].id },
      { name: 'Gori', CountryId: CountryRows[10].id },
      { name: 'Poti', CountryId: CountryRows[10].id },
      { name: 'Samtredia', CountryId: CountryRows[10].id },
      { name: 'Khashuri', CountryId: CountryRows[10].id },
      { name: 'Senaki', CountryId: CountryRows[10].id },
      // Молдова
      { name: 'Chisinau', CountryId: CountryRows[11].id },
      { name: 'Tiraspol', CountryId: CountryRows[11].id },
      { name: 'Bălți', CountryId: CountryRows[11].id },
      { name: 'Bender', CountryId: CountryRows[11].id },
      { name: 'Rîbnița', CountryId: CountryRows[11].id },
      { name: 'Cahul', CountryId: CountryRows[11].id },
      { name: 'Ungheni', CountryId: CountryRows[11].id },
      { name: 'Soroca', CountryId: CountryRows[11].id },
      { name: 'Orhei', CountryId: CountryRows[11].id },
      { name: 'Dubăsari', CountryId: CountryRows[11].id },
    ];

    await queryInterface.bulkInsert('Cities', citiesData, {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Cities', null, {});
  },
};
